#!/bin/sh
srcdir=`dirname $0`
if [ -e $srcdir/version ] ; then
    echo '#define GIT_VERSION "'`cat $srcdir/version`'"'  >version.h.new
elif git rev-parse --is-inside-work-tree >/dev/null 2>&1 ; then
    echo '#define GIT_VERSION "'`date -u +%Y%m%d`-`git describe --long --dirty --always`'"' >version.h.new
fi
cmp -s version.h version.h.new
if (($? > 0)); then
    mv version.h.new version.h
else
    rm version.h.new
fi
